;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        c-electric-slash
        counsel-yank-pop
        end-of-visual-line
        hungry-delete-forward
        kill-region
        org-cycle
        org-delete-char
        org-self-insert-command
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
