;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        hungry-delete-forward
        org-beginning-of-line
        org-self-insert-command
        org-yank
        sp-splice-sexp
        wdired-finish-edit
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ivy-next-history-element
        ))
